Feature/pwn 7466
p2p-org/p2p-wallet-ios pull request #1011
Opened 2023-03-05 17:16 UTC by TrGiLong

## Description of the changes
-

2023-04-17 08:31 UTC, bigearsenal commented on p2p_wallet/Coordinators/TabBar/ActionsCoordinator.swift
> +                    }
ReceiveCoordinator is removed? Is it a placeholder or am I missing something?

2023-04-17 08:51 UTC, bigearsenal commented on p2p_wallet/Extensions/Combine/Publisher+asyncMap.swift
> +    func weakAssign<T: AnyObject>(
We already had assignWeak from `develop`, please remove this function

2023-04-18 07:13 UTC, sidorov-panda requested changes

2023-04-18 07:13 UTC, sidorov-panda commented on Packages/KeyAppKit/Sources/KeyAppKitCore/Blockchain/AnyToken.swift
> +public protocol AnyToken {
Name of the protocol is commonly used for Opaque Type pattern. Please rename it

2023-04-26 12:21 UTC, merged