[PWN-7830] Load history from the init
p2p-org/p2p-wallet-ios pull request #1110
Opened 2023-03-30 13:13 UTC by lisemyon

## Description of the changes
-

2023-03-30 13:19 UTC, lisemyon commented on p2p_wallet/Scenes/Main/History/New/HistoryView.swift
>              viewModel.fetch()
I left it here to keep actual data every time history is opened

2023-04-10 08:49 UTC, TrGiLong submitted a review, later dismissed

2023-04-10 21:05 UTC, bigearsenal requested changes
Please resolve conflict

2023-04-11 07:55 UTC, lisemyon commented
> Please resolve conflict

done

2023-04-11 08:24 UTC, bigearsenal approved these changes

2023-04-12 09:45 UTC, merged