[PWN-8205] Display accountName with @ on send transactions, history s…
p2p-org/p2p-wallet-ios pull request #1187
Opened 2023-04-26 12:23 UTC by lisemyon

…creens

## Description of the changes
-

2023-04-26 12:30 UTC, bigearsenal approved these changes

2023-04-26 12:31 UTC, bigearsenal requested changes
Please resolve conflict

2023-04-26 12:49 UTC, bigearsenal submitted a review, later dismissed

2023-05-19 11:14 UTC, sidorov-panda approved these changes

2023-05-19 11:19 UTC, TrGiLong approved these changes

2023-05-19 11:19 UTC, TrGiLong approved these changes

2023-05-22 00:26 UTC, merged