[PWN-8785] Get rid of search field in Source of funds and Occupation windows
p2p-org/p2p-wallet-ios pull request #1342
Opened 2023-06-05 10:22 UTC by lisemyon

## Description of the changes
-

2023-06-05 10:38 UTC, sidorov-panda requested changes

2023-06-05 10:38 UTC, sidorov-panda commented on p2p_wallet/Extensions/View+Extensions.swift
> +    func asViewController(withoutUIKitNavBar: Bool = true, ignoresKeybaord: Bool = false) -> UIViewController {
mistype

2023-06-05 16:23 UTC, lisemyon commented on p2p_wallet/Extensions/View+Extensions.swift
> +    func asViewController(withoutUIKitNavBar: Bool = true, ignoresKeybaord: Bool = false) -> UIViewController {
thx, fixed

2023-06-06 00:48 UTC, bigearsenal approved these changes

2023-06-15 08:49 UTC, merged