Fix race condition during loading tokens
p2p-org/p2p-wallet-ios pull request #1704
Opened 2024-02-15 13:14 UTC by TrGiLong

## Description of the changes
-

2024-02-15 13:19 UTC, bigearsenal requested changes

2024-02-15 13:19 UTC, bigearsenal commented on Packages/KeyAppKit/Sources/TokenService/Solana/SolanaTokenService.swift
> +        setupTask = Task {
Since `setupTask` store strong `self` and `self` stores `setupTask`, there will be retain cycle here.

2024-02-15 14:47 UTC, TrGiLong commented on Packages/KeyAppKit/Sources/TokenService/Solana/SolanaTokenService.swift
> +        setupTask = Task {
setupTask = nil after running

2024-02-15 16:55 UTC, bigearsenal commented on Packages/KeyAppKit/Sources/TokenService/Solana/SolanaTokenService.swift
> +        setupTask = Task {
Why don't we just capture [weak self]?

2024-02-16 07:42 UTC, bigearsenal approved these changes

2024-02-16 15:05 UTC, merged