iOS. 8: Transaction process state
p2p-org/p2p-wallet-ios pull request #254
Opened 2022-05-17 15:12 UTC by qwerkly

## Description of the changes
-

2022-05-17 15:31 UTC, TrGiLong submitted a review, later dismissed

2022-05-18 00:31 UTC, bigearsenal requested changes

2022-05-18 00:31 UTC, bigearsenal commented on p2p_wallet/UIKit/Loaders/AnimatedProgressLayer.swift
> +        else if key == #keyPath(color) { return true }
Swiftlint violation

2022-05-18 08:56 UTC, TrGiLong approved these changes

2022-05-18 09:07 UTC, TrGiLong approved these changes

2022-10-26 12:33 UTC, closed without merging