Seed phrase screen new design
p2p-org/p2p-wallet-ios pull request #32
Opened 2021-11-18 07:57 UTC by OldCrab

2021-11-18 10:14 UTC, bigearsenal requested changes

2021-11-18 10:14 UTC, bigearsenal commented on p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/EnterSeedViewController/EnterSeedInfo/EnterSeedInfoNavigationBar.swift
> +final class EnterSeedInfoNavigationBar: WLNavigationBar {
subview of a scene must be implemented in scene's extension
```swift
extension EnterSeedInfo {
    final class NavigationBar: WLNavigationBar
}
```
The same for EnterSeedNavigationBar

2021-11-18 10:14 UTC, bigearsenal commented on p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/EnterSeedViewController/EnterSeedMainButtonContent.swift
> +enum EnterSeedMainButtonContent {
Enum that releated to a scene should be defined inside that scene.
Let's add this enum MainButtonContent inside EnterSeed.swift, after NavigatableScene, the same for InvalidationReason.
Avoid polluting global namespace

2021-11-19 03:58 UTC, bigearsenal commented
ADDITIONAL TASK: https://p2pvalidator.atlassian.net/browse/P2PW-1088
![image](https://user-images.githubusercontent.com/6975538/142562556-0ae60a1c-4ddc-4a94-ad16-5224a6660bdc.png)

2021-11-19 14:46 UTC, bigearsenal approved these changes

2021-11-19 14:46 UTC, bigearsenal commented on p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/EnterSeedViewController/EnterSeed.RootView.swift
> +        private let agreeTermsAndConditionsView = AgreeTermsAndConditionsView()
AgreeTermsAndConditionsView.swift file not found

2021-11-19 14:47 UTC, bigearsenal requested changes

2021-11-19 14:47 UTC, bigearsenal commented on p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateSecurityKeys/CreateSecurityKeys.RootView.swift
> +        private let agreeTermsAndConditions = AgreeTermsAndConditionsView()
![image](https://user-images.githubusercontent.com/6975538/142641668-201c8229-bd78-4ff1-923f-e54fdd3c5f86.png)
AgreeTermsAndConditionsView: file not found

2021-11-24 06:41 UTC, bigearsenal requested changes
remove THPinViewController from your local repository
```rm -rf THPinViewController```

2021-11-24 06:46 UTC, bigearsenal requested changes
The TermsAndConditionsVC has been removed from develop, so let's remove `TermsAndConditionsVC`, use `WLMarkdownVC(title: L10n.termsOfUse.uppercaseFirst, bundledMarkdownTxtFileName: "Terms_of_service")` instead

2021-11-24 15:08 UTC, OldCrab commented
> 



> The TermsAndConditionsVC has been removed from develop, so let's remove `TermsAndConditionsVC`, use `WLMarkdownVC(title: L10n.termsOfUse.uppercaseFirst, bundledMarkdownTxtFileName: "Terms_of_service")` instead

Can't find a place to remove, I thought I've already done it

2021-11-24 23:55 UTC, bigearsenal commented
> > 
> 
> > The TermsAndConditionsVC has been removed from develop, so let's remove `TermsAndConditionsVC`, use `WLMarkdownVC(title: L10n.termsOfUse.uppercaseFirst, bundledMarkdownTxtFileName: "Terms_of_service")` instead
> 
> Can't find a place to remove, I thought I've already done it

Oh. I see, the file has been removed from the .xcodeproj, but still remains on repository.
I will approve this PR and remove upon merging. Thanks

2021-11-24 23:56 UTC, bigearsenal approved these changes

2021-11-24 23:56 UTC, merged