[PWN-5957] Create coordinators, where it's needed
p2p-org/p2p-wallet-ios pull request #716
Opened 2022-11-15 07:03 UTC by qwerkly

## Description of the changes
-

2022-11-28 15:13 UTC, sidorov-panda requested changes

2022-11-28 15:13 UTC, sidorov-panda commented on p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift
> +                debugPrint("loool")
remove?

2022-11-28 15:13 UTC, sidorov-panda commented on p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift
> +//        let coordinator = MainCoordinator(window: window, authenticateWhenAppears: showAuthenticationOnMainOnAppear)
remove?

2022-11-28 15:13 UTC, sidorov-panda commented on p2p_wallet/Coordinators/SwapCoordinator.swift
> +        return subject.eraseToAnyPublisher()
prefix(1)

2022-11-28 15:13 UTC, sidorov-panda commented on p2p_wallet/Coordinators/SendCoordinator.swift
> +        return subject.eraseToAnyPublisher()
prefix(1)

2022-11-28 15:13 UTC, sidorov-panda commented on p2p_wallet/Coordinators/TabBar/TabBarCoordinator.swift
> +        debugPrint("--- TabBarCoordinator deinit")
remove?

2022-11-28 15:13 UTC, sidorov-panda commented on p2p_wallet/Coordinators/WalletDetailCoordinator.swift
> +        return subject.eraseToAnyPublisher()
prefix(1)

2022-11-28 15:18 UTC, sidorov-panda requested changes

2022-11-28 15:18 UTC, sidorov-panda commented on p2p_wallet/Coordinators/TabBar/HomeCoordinator.swift
> +                let coordinator = SendCoordinator(navigationController: navigationController, pubKey: nil)
flatMap

2022-11-28 15:18 UTC, sidorov-panda commented on p2p_wallet/Coordinators/TabBar/HomeCoordinator.swift
> +                let coordinator = SwapCoordinator(navigationController: navigationController, initialWallet: nil)
flatMap

2022-11-28 15:18 UTC, sidorov-panda commented on p2p_wallet/Scenes/TabBar/TabBarController.swift
> +        print("lololool")
erase?

2022-12-15 05:57 UTC, bigearsenal submitted a review, later dismissed

2022-12-23 07:54 UTC, bigearsenal commented
Dupplicated https://github.com/p2p-org/p2p-wallet-ios/pull/823
Will merge with [823](https://github.com/p2p-org/p2p-wallet-ios/pull/823)

2022-12-23 07:54 UTC, closed without merging